[tool.poetry]
name = "ai"
version = "0.1.0"
description = "A brief description"
authors = ["Sankar Boro <sankar.boro@yahoo.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
tiktoken = ">=0.9.0,<0.10.0"
torch = ">=2.7.1,<3.0.0"
matplotlib = ">=3.10.8,<4.0.0"

# Optional (commented)
# torchvision = ">=0.22.1,<0.23.0"
# torchaudio = ">=2.7.1,<3.0.0"